#!/bin/bash
# ckb auto build/install script

# Temporary files for program output
TMPFILE=$(mktemp /tmp/ckb.XXXXXXXX)
function newtmp {
    rm -f "$TMPFILE"
    TMPFILE=$(mktemp /tmp/ckb.XXXXXXXX)
}

# Check for failure, quit if unsuccessful
function checkfail {
    if [[ $1 -ne 0 ]]; then
        cat "$TMPFILE"
        finish "$1"
    fi
}

# Exit function
function finish {
    rm -f "$TMPFILE"
    echo ""
    echo "Press enter to exit."
    read -rs dummy
    exit "$1"
}

# Directories
cd "$(dirname "$0")" || exit
SRCDIR="src"
BINDIR="bin"

# This script respects the PREFIX variable on Linux (always /Applications on OSX)
[[ $PREFIX == "" ]] && PREFIX="/usr"

tab=$'\t'
bad_chars=" |'|$tab" # characters needed to be escaped
if [[ "$(pwd)" =~ $bad_chars ]]; then
    echo "Error: you must compile ckb in a directory with no spaces/single quotes/tabs."
    echo "Move or rename the folder and try again."
    finish 1
fi

# Purge old animations on Linux
if [ -d "/usr/bin/ckb-animations" ]; then
    echo "Found deprecated installation scheme, fixing"
    rm -rf "/usr/bin/ckb-animations"
    checkfail $?
    echo "Done"
fi

if [[ -d $SRCDIR ]]; then
    echo "Preparing build files..."
    # Clean up first
    make clean >/dev/null 2>&1
    rm -f Makefile Makefile.* ./*/*/Makefile ./*/*/Makefile.* >/dev/null 2>&1
    # Generate makefiles
    ./qmake-auto "$QMAKEFLAGS" > "$TMPFILE" 2>&1
    checkfail $?
    make clean >/dev/null 2>&1
    # Run make with command arguments
    echo "Compiling binaries..."
    echo "(This can take a while, please be patient)"
    newtmp
    # Find out how many cores the system has, for make
    JOBS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
    # Default to 2 jobs if something went wrong earlier
    if [[ -z "$JOBS" ]]; then
        JOBS=2
    fi
    make -j "$JOBS" "$@" 2>"$TMPFILE"
    checkfail $?
    echo ""
    echo "Finished!"
fi
if [[ ! -d $BINDIR ]]; then
    # No binaries and no source ($SRCDIR branch will surely create $BINDIR or die trying)
    echo "There is nothing to do."
    finish 0
fi


# Linux
newtmp
# Install apps
mkdir -p "$PREFIX/bin"
mkdir -p "$PREFIX/lib"
checkfail $?
install bin/ckb "$PREFIX/bin/ckb" 2>"$TMPFILE"
checkfail $?
install bin/ckb-daemon "$PREFIX/bin/ckb-daemon" 2>"$TMPFILE"
checkfail $?
mkdir -p "$PREFIX/lib/ckb-animations" 2>"$TMPFILE"
checkfail $?
install bin/ckb-animations/* "$PREFIX/lib/ckb-animations" 2>"$TMPFILE"
checkfail $?

exit 0
